# Generated by Django 2.2.5 on 2019-12-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='book2',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dress',
            fields=[
                ('dressid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('data', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('password', models.IntegerField()),
            ],
        ),
    ]
