# Generated by Django 2.2.5 on 2019-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.IntegerField(auto_created=True),
        ),
    ]
