# Generated by Django 2.2.5 on 2019-12-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0002_auto_20191210_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userid',
        ),
    ]
