# Generated by Django 2.2.5 on 2019-12-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0004_auto_20191211_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book3',
            name='userid',
        ),
    ]
