# Generated by Django 2.2.5 on 2019-12-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0005_remove_book3_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book3',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
