# Generated by Django 2.2.5 on 2019-12-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0006_auto_20191211_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='users1',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
