# Generated by Django 2.2.5 on 2019-12-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0009_auto_20191223_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users2',
            old_name='DOB',
            new_name='birth',
        ),
    ]
