# Generated by Django 2.2.5 on 2019-12-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0010_auto_20191223_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users2',
            old_name='birth',
            new_name='date',
        ),
    ]
