# Generated by Django 2.2.5 on 2019-12-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0011_auto_20191223_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='users3',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='users2',
        ),
    ]
