# Generated by Django 2.2.5 on 2019-12-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0013_auto_20191228_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book4',
            old_name='dressid',
            new_name='drssid',
        ),
    ]
