# Generated by Django 2.2.5 on 2019-12-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0015_auto_20191228_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book5',
            old_name='price',
            new_name='itemid',
        ),
        migrations.RemoveField(
            model_name='book5',
            name='name',
        ),
    ]
