# Generated by Django 2.2.5 on 2019-12-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0017_auto_20191228_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book6',
            name='drsid',
        ),
    ]
