# Generated by Django 2.2.5 on 2019-12-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0018_remove_book6_drsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='book7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.IntegerField()),
                ('drs', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='book6',
        ),
    ]
