# Generated by Django 2.2.5 on 2019-12-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0019_auto_20191228_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book7',
            name='drs',
        ),
    ]
