# Generated by Django 2.2.5 on 2019-12-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0020_remove_book7_drs'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
            ],
        ),
    ]
