# Generated by Django 2.2.5 on 2019-12-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0022_auto_20191228_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
    ]
