# Generated by Django 2.2.5 on 2019-12-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0023_auto_20191229_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='feedbacks',
        ),
        migrations.RenameField(
            model_name='feedbacks',
            old_name='comments',
            new_name='comment',
        ),
    ]
