# Generated by Django 2.2.5 on 2019-12-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0025_auto_20191230_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback11',
        ),
    ]
