# Generated by Django 2.2.5 on 2020-01-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0026_auto_20191230_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='users4',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='users3',
        ),
    ]
