# Generated by Django 2.2 on 2020-01-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0027_auto_20200102_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='book8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='book7',
        ),
    ]
