# Generated by Django 2.2 on 2020-01-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0028_auto_20200113_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='status1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book8',
            name='status',
        ),
    ]
