# Generated by Django 2.2 on 2020-01-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0029_auto_20200114_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status1',
        ),
    ]
