# Generated by Django 2.2 on 2020-01-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0030_delete_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book8',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
