# Generated by Django 2.2 on 2020-01-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0031_book8_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book8',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
