# Generated by Django 2.2.5 on 2020-01-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0032_auto_20200114_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book8',
            new_name='book10',
        ),
    ]
